apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: defaultadminbinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespaceadmin
subjects:
- kind: ServiceAccount
  name: default
